config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :widgets
  
  get 'exchanges/index'
  resources :exchanges

  get 'wallets/index'
  resources :wallets
  get 'about/index'

  get 'welcome/index'
  resources :about

end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def index
  end
  
  def show
    if( params[:p] == nil )   # This logic sets the default pair to BTC_ETH
      pair = 'BTC_ETH'        # It also avoids a nil value being assigned to pair
    else
      pair = params[:p]
    end
    
    if( params[:tf] == nil )    # This logic sets the default timeframe to 6 hours
      @frame = 6.hours          # It also avoids a nil value being assigned to @frame
    else
      @frame = eval(params[:tf])
    end
    
    if( params[:all] == 'true' )     # Sets @all variable to be true if all exhanges are wanted
      @all = true
    elsif( params[:all] == 'false' )   # Sets @all variable to be false if one exchange is wanted
      @all = false
    end
    
    @pair1 = pair[0..2]             # First part of pair
    @pair2 = pair[4..-1]            # Second part of pair
    @pair = "#{@pair1}_#{@pair2}"   # Entire pair
    
    @exchange = params[:x]  # Exchange value
    
    case @frame
      when 6.hours
        interval = 300      # For a 6-hour timeframe, use 5 minute candles
      when 1.day
        interval = 3600     # For a day-long timeframe, use 1 hour candles
      when 1.week
        interval = 43200    # For a week-long timeframe, use 12 hour candles
      when 1.month
        interval = 86400    # For a month-long timeframe, use 24 hour candles
    end
    
    # Minimum and maximum verticle axis values will be calculated from these values
    @min = Candlestick.where( :timestamp => (Time.now - @frame)..(Time.now), :exchange => @exchange, :pair => pair, :interval => interval ).minimum(:low)
    @max = Candlestick.where( :timestamp => (Time.now - @frame)..(Time.now), :exchange => @exchange, :pair => pair, :interval => interval ).maximum(:high)
    
    # Sets up the data variable based on if it wants one or multiple series
    if( @all == false )
      # Assigns the appropriate data to @candles, according the the exchange, pair, and interval data
      @candles = Candlestick.order( :timestamp ).where( :timestamp => (Time.now - @frame)..(Time.now),
                :exchange => @exchange, :pair => pair, :interval => interval ).pluck( :timestamp, :low, :open, :close, :high )
      
      # Sets up the label information for the legend
      labels = [ '', @exchange, '', '', '' ]
      @candles = @candles.unshift( labels )
      
    # Sets up the @candles array to display multiple series
    else
      @candles = Candlestick.order( :timestamp ).where( :timestamp => (Time.now - @frame)..(Time.now),
                :exchange => "Bittrex", :pair => pair, :interval => interval ).pluck( :timestamp, :low, :open, :close, :high )
      
      @candles2 = Candlestick.order( :timestamp ).where( :timestamp => (Time.now - @frame)..(Time.now),
                :exchange => "Poloniex", :pair => pair, :interval => interval ).pluck( :timestamp, :low, :open, :close, :high )
      
      # Accounts for the case where BTC_ZEC or BTC_SC pairs are shown (Bitfinex doesn't have these)
      unless( :pair == 'BTC_ZEC' || :pair == 'BTC_SC' )
      
        # Calculates the new mins and maxes
        @min = Candlestick.where( :timestamp => (Time.now - @frame)..(Time.now), :pair => pair, :interval => interval ).minimum(:low)
        @max = Candlestick.where( :timestamp => (Time.now - @frame)..(Time.now), :pair => pair, :interval => interval ).maximum(:high)
      
        @candles3 = Candlestick.order( :timestamp ).where( :timestamp => (Time.now - @frame)..(Time.now),
                  :exchange => "Bitfinex", :pair => pair, :interval => interval ).pluck( :timestamp, :low, :open, :close, :high )
      end
      
      i = 0            
      @candles.each do |candle|   # Combines the first and second series so the graph can render them
        
        # Ensures that empty spots in a series are taken care of
        if( @candles2[i] != nil && candle[0] == @candles2[i][0] )
            candle.push( @candles2[i][1], @candles2[i][2], @candles2[i][3], @candles2[i][4] )
            i = i + 1
          else
            candle.push( 0, 0, 0, 0 )
            i = i + 1
          end
          
      end
      
      # Combines the third series, if it's not BTC_ZEC or BTC_SC
      unless( @pair == 'BTC_ZEC' || @pair == 'BTC_SC' )
        i = 0
        @candles.each do |candle|
          
          # Ensures that empty spots in a series are taken care of
          if( @candles3[i] != nil && candle[0] == @candles3[i][0] )
            candle.push( @candles3[i][1], @candles3[i][2], @candles3[i][3], @candles3[i][4] )
            i = i + 1
          else
            candle.push( 0, 0, 0, 0 )
            i = i + 1
          end
          
        end
      end
      
      # This sets up the legend for the chart to interpret
      if( @pair == 'BTC_ZEC' || @pair == 'BTC_SC' )
        labels = [ '', 'Bittrex', '', '', '', 'Poloniex', '', '', '' ]
      else
        labels = [ '', 'Bittrex', '', '', '', 'Poloniex', '', '', '', 'Bitfinex', '', '', '' ]
      end
      
      # Puts the labels array at the beggining of @candles, and shifts the rest forward one index
      @candles = @candles.unshift( labels )
      
    end
  
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/index.html.erb
<!DOCTYPE html>
<html>
    <script language="javascript">
        var bittrix = document.getElementById("bittrex");
        bittrex.addEventListener("mouseover", bittrexMouseover, false);
        bittrex.addEventListener("mouseout", bittrexMouseout, false);    
        
        function bittrexMouseover() {
          document.getElementById("bittrex_fees").setAttribute("style", "display:block;")
        }
      
        function bittrexMouseout() {
          document.getElementById("bittrex_fees").setAttribute("style", "display:none;")
        }
        
        var poloniex = document.getElementById("poloniex");
        poloniex.addEventListener("mouseover", poloniexMouseover, false);
        poloniex.addEventListener("mouseout", poloniexMouseout, false);
        
        function poloniexMouseover() {
          document.getElementById("poloniex_fees").setAttribute("style", "display:block;")
        }
      
        function poloniexMouseout() {
          document.getElementById("poloniex_fees").setAttribute("style", "display:none;")
        }
    
        var bitfinex = document.getElementById("bitfinex");
        bitfinex.addEventListener("mouseover", bitfinexMouseover, false);
        bitfinex.addEventListener("mouseout", bitfinexMouseout, false);
        
        function bitfinexMouseover() {
          document.getElementById("bitfinex_fees").setAttribute("style", "display:block;")
        }
      
        function bitfinexMouseout() {
          document.getElementById("bitfinex_fees").setAttribute("style", "display:none;")
        }
    </script>
    <style>
        div#bittrex_fees {
            display: none;
        }
        div#poloniex_fees {
            display: none;
        }
        div#bitfinex_fees {
            display: none;
        }
    </style>
    <meta charset="UTF-8">
    <head>
        <title>Exchanges</title>
        <link rel="stylesheet" type="text/css" href="/stylesheets/basic_style.css">
    </head>
    <body>
        <%= render "header/header" %>
        <br><br>
        <div style="margin: 0 auto; width: 850px;">
        <f class="smaller">Click an exchange below to access the Cryptogator application.</f>
        <br><br><br>
        </div>
        <div style="margin: 0 auto; width: 400px;">
            <div style="margin: 10 auto; width: 400px;"><f>Supported Exchanges:</f></div>
            <br>
                <a href = "exchanges/show/?all=false&x=Bittrex" id="exchanges" target = "_blank"><div id='bittrex' style="display: inline-block;"><img src='/images/exchange buttons/bittrex_unselected.png' onmouseover="this.src='/images/exchange buttons/bittrex_selected.png';" onmouseout="this.src='images/exchange buttons/bittrex_unselected.png';"/></div></a>
                <a href = "exchanges/show/?all=false&x=Poloniex" id="exchanges" target = "_blank"><div id='poloniex' style="display: inline-block;"><img src='/images/exchange buttons/poloniex_unselected.png' onmouseover="this.src='/images/exchange buttons/poloniex_selected.png';" onmouseout="this.src='images/exchange buttons/poloniex_unselected.png';"/></div></a>
                <a href = "exchanges/show/?all=false&x=Bitfinex" id="exchanges" target = "_blank"><div id='bitfinex' style="display: inline-block;"><img src='/images/exchange buttons/bitfinex_unselected.png' onmouseover="this.src='/images/exchange buttons/bitfinex_selected.png';" onmouseout="this.src='images/exchange buttons/bitfinex_unselected.png';"/></div></a>
        </div>
        <div style="margin: 0 auto; width: 610px;">
            <div id='bittrex_fees'><img src='/images/exchange buttons/bittrex_fees.png' /></div>
            <div id='poloniex_fees'><img src='/images/exchange buttons/poloniex_fees.png' /></div>
            <div id='bitfinex_fees'><img src='/images/exchange buttons/bitfinex_fees.png' /></div>
        </div>
    </body>
</html>

app/views/exchanges/show.html.erb
<!-- This is the tag that holds the chart -->
<div id="chart_div" style="width: 1200px; height: 600px;"></div>

<div id="buttons">
<!-- These are the buttons that manipulate the graph sets and properties -->
<%= link_to "BTC/ETH", exchange_path( :all => "false", :x => @exchange, :p => "BTC_ETH", :tf => @frame ), { :class=>"exchange_button" } %>
<%= link_to "All Exchanges", exchange_path( :all => "true", :x => @exchange, :p => "BTC_ETH", :tf => @frame ), { :class=>"exchange_button" } %><br><br><br>
<%= link_to "BTC/XMR", exchange_path( :all => "false", :x => @exchange, :p => "BTC_XMR", :tf => @frame ), { :class=>"exchange_button" } %>
<%= link_to "All Exchanges", exchange_path( :all => "true", :x => @exchange, :p => "BTC_XMR", :tf => @frame ), { :class=>"exchange_button" } %><br><br><br>
<%= link_to "BTC/DASH", exchange_path( :all => "false", :x => @exchange, :p => "BTC_DASH", :tf => @frame ), { :class=>"exchange_button" } %>
<%= link_to "All Exchanges", exchange_path( :all => "true", :x => @exchange, :p => "BTC_DASH", :tf => @frame ), { :class=>"exchange_button" } %><br><br><br>
<%= link_to "BTC/LTC", exchange_path( :all => "false", :x => @exchange, :p => "BTC_LTC", :tf => @frame ), { :class=>"exchange_button" } %>
<%= link_to "All Exchanges", exchange_path( :all => "true", :x => @exchange, :p => "BTC_LTC", :tf => @frame ), { :class=>"exchange_button" } %><br><br><br>
<%= link_to "BTC/XRP", exchange_path( :all => "false", :x => @exchange, :p => "BTC_XRP", :tf => @frame ), { :class=>"exchange_button" } %>
<%= link_to "All Exchanges", exchange_path( :all => "true", :x => @exchange, :p => "BTC_XRP", :tf => @frame ), { :class=>"exchange_button" } %><br><br><br>

<!-- Bitfinex doesn't have the BTC/ZEC and BTC/SC pairs -->
<% if( @exchange != "Bitfinex" ) %>
    <%= link_to "BTC/ZEC", exchange_path( :all => "false", :x => @exchange, :p => "BTC_ZEC" ), { :class=>"exchange_button" } %>
    <%= link_to "All Exchanges", exchange_path( :all => "true", :x => @exchange, :p => "BTC_ZEC", :tf => @frame ), { :class=>"exchange_button" } %><br><br><br>
    <%= link_to "BTC/SC", exchange_path( :all => "false", :x => @exchange, :p => "BTC_SC" ), { :class=>"exchange_button" } %>
    <%= link_to "All Exchanges", exchange_path( :all => "true", :x => @exchange, :p => "BTC_SC", :tf => @frame ), { :class=>"exchange_button" } %><br><br><br><br><br><br>
<% else %>
    <br><br><br>
<% end %>

<%= link_to "6h", exchange_path( :all => @all.to_s, :x => @exchange, :p => @pair, :tf => 6.hours ), { :class=>"exchange_button" } %>
<%= link_to "1D", exchange_path( :all => @all.to_s, :x => @exchange, :p => @pair, :tf => 1.day ), { :class=>"exchange_button" } %>
<%= link_to "1W", exchange_path( :all => @all.to_s, :x => @exchange, :p => @pair, :tf => 1.week ), { :class=>"exchange_button" } %>
<%= link_to "1M", exchange_path( :all => @all.to_s, :x => @exchange, :p => @pair, :tf => 1.month ), { :class=>"exchange_button" } %>
</div>

<!-- These are tags that hold data from the controller -->
<!-- candleChart.js will use this data to form the graph -->
<div id="candles" data-temp="<%= @candles.to_json %>" />
<div id="exchange" data-temp=<%= raw @exchange.to_json %> />
<div id="pair1" data-temp=<%= raw @pair1.to_json %> />
<div id="pair2" data-temp=<%= raw @pair2.to_json %> />
<div id="all" data-temp=<%= raw @all.to_json %> />
<div id="min" data-temp="<%= raw @min.to_json %>" />
<div id="max" data-temp="<%= raw @max.to_json %>" />